/* hyperbolic.js — regular {p,q} tiling on the Poincaré disk (Circle Limit style)
 *
 * Strategy: build the central regular p-gon (vertices at Euclidean radius r0,
 * edges = geodesics). The reflection group is generated by inversions R_k in the
 * p edge-circles. Every tile is g(centralPolygon) for a word g in those
 * generators; the neighbour of tile g across edge k is the tile g.Rk. We BFS the
 * Cayley graph, dedup by tile centre, and map the user's motif through each g so
 * it shrinks and curves correctly toward the boundary.
 */
window.Escher = window.Escher || {};
Escher.hyperbolic = (function () {
  "use strict";
  var G = Escher.geom;

  function valid(p, q) { return (p - 2) * (q - 2) > 4; }

  // Build fixed data for a {p,q} tiling: central boundary samples, edge
  // reflection functions, and the central-cell motif strokes.
  function build(design) {
    var p = design.hyper.p, q = design.hyper.q;
    if (!valid(p, q)) { p = 5; q = 4; }
    var pi = Math.PI;
    var r0 = Math.sqrt(Math.cos(pi / p + pi / q) / Math.cos(pi / p - pi / q));
    var rot = -pi / 2 + pi / p;     // orient with a flat-ish bottom

    var verts = [];
    for (var k = 0; k < p; k++) {
      var a = rot + 2 * pi * k / p;
      verts.push({ x: r0 * Math.cos(a), y: r0 * Math.sin(a) });
    }

    // Per edge: reflection function + sampled geodesic arc (V_k -> V_{k+1}).
    var reflectors = [];
    var boundary = [];
    var SAMP = 16;
    for (var e = 0; e < p; e++) {
      var A = verts[e], B = verts[(e + 1) % p];
      var lenA = A.x * A.x + A.y * A.y;
      var Astar = { x: A.x / lenA, y: A.y / lenA };   // inverse point through unit circle
      var circ = G.circle3(A, B, Astar);
      if (circ && isFinite(circ.r) && circ.r < 1e5) {
        (function (C) {
          reflectors.push(function (z) {
            var dx = z.x - C.x, dy = z.y - C.y;
            var d2 = dx * dx + dy * dy;
            var f = (C.r * C.r) / d2;
            return { x: C.x + dx * f, y: C.y + dy * f };
          });
        })(circ);
        // sample the minor arc from A to B
        var a1 = Math.atan2(A.y - circ.y, A.x - circ.x);
        var a2 = Math.atan2(B.y - circ.y, B.x - circ.x);
        var da = a2 - a1;
        while (da > pi) da -= 2 * pi;
        while (da < -pi) da += 2 * pi;
        for (var s = 0; s < SAMP; s++) {
          var t = a1 + da * (s / SAMP);
          boundary.push({ x: circ.x + circ.r * Math.cos(t), y: circ.y + circ.r * Math.sin(t) });
        }
      } else {
        // geodesic is a diameter → reflect across the line through origin
        var nx = -(B.y - A.y), ny = (B.x - A.x);
        var nl = Math.hypot(nx, ny); nx /= nl; ny /= nl;
        (function (nX, nY) {
          reflectors.push(function (z) {
            var d = 2 * (z.x * nX + z.y * nY);
            return { x: z.x - d * nX, y: z.y - d * nY };
          });
        })(nx, ny);
        for (var s2 = 0; s2 < SAMP; s2++) {
          var tt = s2 / SAMP;
          boundary.push({ x: A.x + (B.x - A.x) * tt, y: A.y + (B.y - A.y) * tt });
        }
      }
    }

    // Map the user's unit-cell strokes into the central polygon.
    var half = r0 * 0.82;
    var centralStrokes = design.strokes.map(function (st) {
      return {
        color: st.color, width: st.width, fill: st.fill,
        points: st.points.map(function (pt) {
          return { x: (pt.x - 0.5) * 2 * half, y: (pt.y - 0.5) * 2 * half };
        })
      };
    });

    return { p: p, q: q, r0: r0, boundary: boundary, reflectors: reflectors, centralStrokes: centralStrokes };
  }

  function compose(T, R) { return function (z) { return T(R(z)); }; }
  var IDENT = function (z) { return { x: z.x, y: z.y }; };

  // BFS the tiling group; return list of {T, parity, depth}.
  function generateCells(model, maxCells) {
    var cells = [];
    var seen = {};
    function key(pt) { return (Math.round(pt.x * 600) ) + "," + (Math.round(pt.y * 600)); }
    var start = { T: IDENT, parity: 0, depth: 0, center: { x: 0, y: 0 } };
    cells.push(start);
    seen[key(start.center)] = true;
    var queue = [start];
    var head = 0;
    while (head < queue.length && cells.length < maxCells) {
      var cur = queue[head++];
      for (var k = 0; k < model.reflectors.length; k++) {
        var nT = compose(cur.T, model.reflectors[k]);
        var center = nT({ x: 0, y: 0 });
        if (center.x * center.x + center.y * center.y > 0.9985) continue; // hugs boundary
        var kk = key(center);
        if (seen[kk]) continue;
        seen[kk] = true;
        var cell = { T: nT, parity: cur.parity ^ 1, depth: cur.depth + 1, center: center };
        cells.push(cell);
        queue.push(cell);
        if (cells.length >= maxCells) break;
      }
    }
    return cells;
  }

  // Pure geometry: returns the tiling already transformed into disk coordinates
  // (x,y in [-1,1]). Shared by the canvas renderer and the SVG exporter.
  function tilesGeom(design, maxCells) {
    var model = build(design);
    var cells = generateCells(model, maxCells || (design.hyper && design.hyper.maxCells) || 360);
    var out = [];
    for (var c = 0; c < cells.length; c++) {
      var T = cells[c].T;
      var bd = new Array(model.boundary.length);
      for (var b = 0; b < model.boundary.length; b++) bd[b] = T(model.boundary[b]);
      var strokes = [];
      for (var s = 0; s < model.centralStrokes.length; s++) {
        var st = model.centralStrokes[s];
        var pts = new Array(st.points.length);
        for (var p = 0; p < st.points.length; p++) pts[p] = T(st.points[p]);
        strokes.push({ color: st.color, fill: st.fill, width: st.width, points: pts });
      }
      out.push({ boundary: bd, strokes: strokes, parity: cells[c].parity, depth: cells[c].depth });
    }
    return { r0: model.r0, p: model.p, q: model.q, tiles: out };
  }

  function render(ctx, W, H, design, opts) {
    opts = opts || {};
    var maxCells = opts.maxCells || (design.hyper && design.hyper.maxCells) || 360;
    var data = tilesGeom(design, maxCells);
    var tiles = data.tiles;

    var cx = W / 2, cy = H / 2;
    var Rpx = Math.min(W, H) * 0.47;
    function toScreen(z) { return { x: cx + z.x * Rpx, y: cy + z.y * Rpx }; }

    // Backdrop + disk.
    ctx.fillStyle = design.colorBg;
    ctx.fillRect(0, 0, W, H);
    ctx.save();
    ctx.beginPath();
    ctx.arc(cx, cy, Rpx, 0, 7);
    ctx.fillStyle = "#0d0c0b";
    ctx.fill();
    ctx.clip();   // never draw outside the disk

    for (var c = 0; c < tiles.length; c++) {
      var t = tiles[c];
      ctx.beginPath();
      var b0 = toScreen(t.boundary[0]);
      ctx.moveTo(b0.x, b0.y);
      for (var i = 1; i < t.boundary.length; i++) {
        var bp = toScreen(t.boundary[i]);
        ctx.lineTo(bp.x, bp.y);
      }
      ctx.closePath();

      // depth shading toward the rim for a sense of infinite recession
      var shade = G.clamp(1 - t.depth * 0.05, 0.45, 1);
      var base = t.parity ? design.colorB : design.colorA;
      ctx.fillStyle = G.mixHex(base, "#0d0c0b", 1 - shade);
      ctx.fill();
      if (design.outline) {
        ctx.strokeStyle = "rgba(15,12,9,.6)";
        ctx.lineWidth = Math.max(0.4, Rpx * 0.004 * shade);
        ctx.stroke();
      }

      // motif, clipped to the cell
      if (t.strokes.length) {
        ctx.save();
        ctx.clip();
        for (var sIdx = 0; sIdx < t.strokes.length; sIdx++) {
          var st = t.strokes[sIdx];
          if (!st.points.length) continue;
          ctx.beginPath();
          var q0 = toScreen(st.points[0]);
          ctx.moveTo(q0.x, q0.y);
          for (var pIdx = 1; pIdx < st.points.length; pIdx++) {
            var qp = toScreen(st.points[pIdx]);
            ctx.lineTo(qp.x, qp.y);
          }
          if (st.fill) {
            ctx.closePath();
            ctx.fillStyle = st.color;
            ctx.fill();
          } else {
            ctx.strokeStyle = st.color;
            ctx.lineWidth = Math.max(0.4, st.width * Rpx / 100 * shade * data.r0);
            ctx.lineJoin = ctx.lineCap = "round";
            ctx.stroke();
          }
        }
        ctx.restore();
      }
    }
    ctx.restore();

    // crisp limit circle
    ctx.beginPath();
    ctx.arc(cx, cy, Rpx, 0, 7);
    ctx.lineWidth = Math.max(1.5, Rpx * 0.01);
    ctx.strokeStyle = "rgba(216,160,75,.85)";
    ctx.stroke();

    return { cells: tiles.length };
  }

  return { render: render, valid: valid, build: build, tiles: tilesGeom };
})();
